### PR TITLE
Fix nickname substituion behaviour

### PR DESCRIPTION
**Pull request by uovobw**
As per #15 a `nicknames` configuration for

```
[[nicknames]]
irc = "some_nick"
telegram = "@some_other_nick"
```
would result in the link

`https://example.com/~some_nick/page.html`

to be sent to telegram as

`https://example.com/~@some_other_nick/page.html`

breaking it badly. This should fix the issue.
It has some limitations, mainly the `nickname_needs_conversion` function could be de-uglyfied and the test improved.

### CODE REVIEW

**Comment by crisidev** [comment]
Nice! And with tests! LGTM.

**Comment by uovobw** [comment]
merging, fixes #15

**Comment by uovobw** [comment]
merging, fixes #15

**Comment by uovobw** [comment]
merging, fixes #15

**Comment by uovobw** [comment]
merging, fixes #15

**Comment by uovobw** [comment]
i have no idea what happened. wow.

**Pull request merged**
